<?php

use Illuminate\Database\Seeder;

class ChairTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
		$chairs=[
		[
			'type'=>1,
			'minQty'=>0,
			'maxQty'=>200,
			'price_per_coveredchair'=>40,
			'price_per_uncoveredchair'=>30,
			'fac_id'=>2,
			'client_id'=>23
		],
		[
			'type'=>1,
			'minQty'=>200,
			'maxQty'=>400,
			'price_per_coveredchair'=>35,
			'price_per_uncoveredchair'=>25,
			'fac_id'=>2,
			'client_id'=>23
		],
		[
			'type'=>1,
			'minQty'=>400,
			'maxQty'=>600,
			'price_per_coveredchair'=>30,
			'price_per_uncoveredchair'=>20,
			'fac_id'=>2,
			'client_id'=>23
		],
		[
			'type'=>1,
			'minQty'=>600,
			'maxQty'=>800,
			'price_per_coveredchair'=>25,
			'price_per_uncoveredchair'=>15,
			'fac_id'=>2,
			'client_id'=>23
		],
		[
			'type'=>1,
			'minQty'=>800,
			'maxQty'=>1000,
			'price_per_coveredchair'=>20,
			'price_per_uncoveredchair'=>12,
			'fac_id'=>2,
			'client_id'=>23
		],
		[
			'type'=>1,
			'minQty'=>1000,
			'maxQty'=>10000,
			'price_per_coveredchair'=>15,
			'price_per_uncoveredchair'=>10,
			'fac_id'=>2,
			'client_id'=>23
		],
		[
			'type'=>2,
			'minQty'=>0,
			'maxQty'=>200,
			'price_per_coveredchair'=>45,
			'price_per_uncoveredchair'=>40,
			'fac_id'=>2,
			'client_id'=>23
		],
		[
			'type'=>2,
			'minQty'=>200,
			'maxQty'=>400,
			'price_per_coveredchair'=>40,
			'price_per_uncoveredchair'=>35,
			'fac_id'=>2,
			'client_id'=>23
		],
		[
			'type'=>2,
			'minQty'=>400,
			'maxQty'=>600,
			'price_per_coveredchair'=>35,
			'price_per_uncoveredchair'=>30,
			'fac_id'=>2,
			'client_id'=>23
		],
		[
			'type'=>2,
			'minQty'=>600,
			'maxQty'=>800,
			'price_per_coveredchair'=>30,
			'price_per_uncoveredchair'=>25,
			'fac_id'=>2,
			'client_id'=>23
		],
		[
			'type'=>2,
			'minQty'=>800,
			'maxQty'=>1000,
			'price_per_coveredchair'=>25,
			'price_per_uncoveredchair'=>20,
			'fac_id'=>2,
			'client_id'=>23
		],
		[
			'type'=>2,
			'minQty'=>1000,
			'maxQty'=>10000,
			'price_per_coveredchair'=>20,
			'price_per_uncoveredchair'=>10,
			'fac_id'=>2,
			'client_id'=>23
		],
		[
			'type'=>3,
			'minQty'=>0,
			'maxQty'=>200,
			'price_per_coveredchair'=>30,
			'price_per_uncoveredchair'=>30,
			'fac_id'=>2,
			'client_id'=>23
		],
		[
			'type'=>3,
			'minQty'=>200,
			'maxQty'=>400,
			'price_per_coveredchair'=>27,
			'price_per_uncoveredchair'=>27,
			'fac_id'=>2,
			'client_id'=>23
		],
		[
			'type'=>3,
			'minQty'=>400,
			'maxQty'=>600,
			'price_per_coveredchair'=>25,
			'price_per_uncoveredchair'=>20,
			'fac_id'=>2,
			'client_id'=>23
		],
		[
			'type'=>3,
			'minQty'=>600,
			'maxQty'=>800,
			'price_per_coveredchair'=>20,
			'price_per_uncoveredchair'=>18,
			'fac_id'=>2,
			'client_id'=>23
		],
		[
			'type'=>3,
			'minQty'=>800,
			'maxQty'=>1000,
			'price_per_coveredchair'=>18,
			'price_per_uncoveredchair'=>15,
			'fac_id'=>2,
			'client_id'=>23
		],
		[
			'type'=>3,
			'minQty'=>1000,
			'maxQty'=>10000,
			'price_per_coveredchair'=>16,
			'price_per_uncoveredchair'=>12,
			'fac_id'=>2,
			'client_id'=>23
		],                                
		[
			'type'=>1,
			'minQty'=>0,
			'maxQty'=>250,
			'price_per_coveredchair'=>55,
			'price_per_uncoveredchair'=>50,
			'fac_id'=>2,
			'client_id'=>24
		],
		[
			'type'=>1,
			'minQty'=>250,
			'maxQty'=>500,
			'price_per_coveredchair'=>50,
			'price_per_uncoveredchair'=>45,
			'fac_id'=>2,
			'client_id'=>24
		],
		[
			'type'=>1,
			'minQty'=>500,
			'maxQty'=>750,
			'price_per_coveredchair'=>45,
			'price_per_uncoveredchair'=>40,
			'fac_id'=>2,
			'client_id'=>24
		],
		[
			'type'=>1,
			'minQty'=>750,
			'maxQty'=>1000,
			'price_per_coveredchair'=>40,
			'price_per_uncoveredchair'=>35,
			'fac_id'=>2,
			'client_id'=>24
		],
		[
			'type'=>1,
			'minQty'=>1000,
			'maxQty'=>10000,
			'price_per_coveredchair'=>38,
			'price_per_uncoveredchair'=>32,
			'fac_id'=>2,
			'client_id'=>24
		],
		[
			'type'=>2,
			'minQty'=>0,
			'maxQty'=>250,
			'price_per_coveredchair'=>60,
			'price_per_uncoveredchair'=>55,
			'fac_id'=>2,
			'client_id'=>24
		],
		[
			'type'=>2,
			'minQty'=>250,
			'maxQty'=>500,
			'price_per_coveredchair'=>55,
			'price_per_uncoveredchair'=>50,
			'fac_id'=>2,
			'client_id'=>24
		],
		[
			'type'=>2,
			'minQty'=>500,
			'maxQty'=>750,
			'price_per_coveredchair'=>50,
			'price_per_uncoveredchair'=>45,
			'fac_id'=>2,
			'client_id'=>24
		],
		[
			'type'=>2,
			'minQty'=>750,
			'maxQty'=>1000,
			'price_per_coveredchair'=>45,
			'price_per_uncoveredchair'=>40,
			'fac_id'=>2,
			'client_id'=>24
		],
		[
			'type'=>2,
			'minQty'=>1000,
			'maxQty'=>10000,
			'price_per_coveredchair'=>40,
			'price_per_uncoveredchair'=>35,
			'fac_id'=>2,
			'client_id'=>24
		],
		[
			'type'=>3,
			'minQty'=>0,
			'maxQty'=>250,
		    'price_per_coveredchair'=>34,
			'price_per_uncoveredchair'=>32,
			'fac_id'=>2,
			'client_id'=>24
		],
		[
			'type'=>3,
			'minQty'=>250,
			'maxQty'=>500,
			'price_per_coveredchair'=>32,
			'price_per_uncoveredchair'=>30,
			'fac_id'=>2,
			'client_id'=>24
		],
		[
			'type'=>3,
			'minQty'=>500,
			'maxQty'=>750,
			'price_per_coveredchair'=>30,
			'price_per_uncoveredchair'=>28,
			'fac_id'=>2,
			'client_id'=>24
		],
		[
			'type'=>3,
			'minQty'=>750,
			'maxQty'=>1000,
			'price_per_coveredchair'=>28,
			'price_per_uncoveredchair'=>26,
			'fac_id'=>2,
			'client_id'=>24
		],
		[
			'type'=>3,
			'minQty'=>1000,
			'maxQty'=>10000,
			'price_per_coveredchair'=>26,
			'price_per_uncoveredchair'=>24,
			'fac_id'=>2,
			'client_id'=>24
		],                        
		[
			'type'=>1,
			'minQty'=>0,
			'maxQty'=>200,
			'price_per_coveredchair'=>65,
			'price_per_uncoveredchair'=>60,
			'fac_id'=>2,
			'client_id'=>25
		],
		[
			'type'=>1,
			'minQty'=>200,
			'maxQty'=>400,
			'price_per_coveredchair'=>60,
			'price_per_uncoveredchair'=>55,
			'fac_id'=>2,
			'client_id'=>25
		],
		[
			'type'=>1,
			'minQty'=>400,
			'maxQty'=>600,
			'price_per_coveredchair'=>55,
			'price_per_uncoveredchair'=>50,
			'fac_id'=>2,
			'client_id'=>25
		],
		[
			'type'=>1,
			'minQty'=>600,
			'maxQty'=>800,
			'price_per_coveredchair'=>50,
			'price_per_uncoveredchair'=>45,
			'fac_id'=>2,
			'client_id'=>25
		],
		[
			'type'=>1,
			'minQty'=>800,
			'maxQty'=>1000,
			'price_per_coveredchair'=>45,
			'price_per_uncoveredchair'=>40,
			'fac_id'=>2,
			'client_id'=>25
		],
		[
			'type'=>1,
			'minQty'=>1000,
			'maxQty'=>10000,
			'price_per_coveredchair'=>40,
			'price_per_uncoveredchair'=>30,
			'fac_id'=>2,
			'client_id'=>25
		],
		[
			'type'=>2,
			'minQty'=>0,
			'maxQty'=>200,
			'price_per_coveredchair'=>35,
			'price_per_uncoveredchair'=>35,
			'fac_id'=>2,
			'client_id'=>25
		],
		[
			'type'=>2,
			'minQty'=>200,
			'maxQty'=>400,
			'price_per_coveredchair'=>32,
			'price_per_uncoveredchair'=>30,
			'fac_id'=>2,
			'client_id'=>25
		],
		[
			'type'=>2,
			'minQty'=>400,
			'maxQty'=>600,
			'price_per_coveredchair'=>30,
			'price_per_uncoveredchair'=>28,
			'fac_id'=>2,
			'client_id'=>21
		],
		[
			'type'=>2,
			'minQty'=>600,
			'maxQty'=>800,
			'price_per_coveredchair'=>28,
			'price_per_uncoveredchair'=>26,
			'fac_id'=>2,
			'client_id'=>25
		],
		[
			'type'=>2,
			'minQty'=>800,
			'maxQty'=>1000,
			'price_per_coveredchair'=>26,
			'price_per_uncoveredchair'=>24,
			'fac_id'=>2,
			'client_id'=>25
		],
		[
			'type'=>2,
			'minQty'=>1000,
			'maxQty'=>10000,
			'price_per_coveredchair'=>24,
			'price_per_uncoveredchair'=>22,
			'fac_id'=>2,
			'client_id'=>25
		],
		[
			'type'=>3,
			'minQty'=>0,
			'maxQty'=>200,
			'price_per_coveredchair'=>58,
			'price_per_uncoveredchair'=>56,
			'fac_id'=>2,
			'client_id'=>25
		],
		[
			'type'=>3,
			'minQty'=>200,
			'maxQty'=>400,
			'price_per_coveredchair'=>56,
			'price_per_uncoveredchair'=>54,
			'fac_id'=>2,
			'client_id'=>25
		],
		[
			'type'=>3,
			'minQty'=>400,
			'maxQty'=>600,
			'price_per_coveredchair'=>54,
			'price_per_uncoveredchair'=>52,
			'fac_id'=>2,
			'client_id'=>25
		],
		[
			'type'=>3,
			'minQty'=>600,
			'maxQty'=>800,
			'price_per_coveredchair'=>52,
			'price_per_uncoveredchair'=>50,
			'fac_id'=>2,
			'client_id'=>25
		],
		[
			'type'=>3,
			'minQty'=>800,
			'maxQty'=>1000,
			'price_per_coveredchair'=>50,
			'price_per_uncoveredchair'=>45,
			'fac_id'=>2,
			'client_id'=>25
		],
		[
			'type'=>3,
			'minQty'=>1000,
			'maxQty'=>10000,
			'price_per_coveredchair'=>45,
			'price_per_uncoveredchair'=>40,
			'fac_id'=>2,
			'client_id'=>25
		],                                    
		
		[
			'type'=>1,
			'minQty'=>0,
			'maxQty'=>200,
			'price_per_coveredchair'=>45,
			'price_per_uncoveredchair'=>40,
			'fac_id'=>2,
			'client_id'=>26
		],
		[
			'type'=>1,
			'minQty'=>200,
			'maxQty'=>400,
			'price_per_coveredchair'=>40,
			'price_per_uncoveredchair'=>35,
			'fac_id'=>2,
			'client_id'=>26
		],
		[
			'type'=>1,
			'minQty'=>400,
			'maxQty'=>600,
			'price_per_coveredchair'=>35,
			'price_per_uncoveredchair'=>30,
			'fac_id'=>2,
			'client_id'=>26
		],
		[
			'type'=>1,
			'minQty'=>600,
			'maxQty'=>800,
			'price_per_coveredchair'=>30,
			'price_per_uncoveredchair'=>25,
			'fac_id'=>2,
			'client_id'=>26
		],
		[
			'type'=>1,
			'minQty'=>800,
			'maxQty'=>1000,
			'price_per_coveredchair'=>25,
			'price_per_uncoveredchair'=>20,
			'fac_id'=>2,
			'client_id'=>26
		],
		[
			'type'=>1,
			'minQty'=>1000,
			'maxQty'=>10000,
			'price_per_coveredchair'=>20,
			'price_per_uncoveredchair'=>15,
			'fac_id'=>2,
			'client_id'=>26
		],
		[
			'type'=>2,
			'minQty'=>0,
			'maxQty'=>200,
			'price_per_coveredchair'=>40,
			'price_per_uncoveredchair'=>28,
			'fac_id'=>2,
			'client_id'=>26
		],
		[
			'type'=>2,
			'minQty'=>200,
			'maxQty'=>400,
			'price_per_coveredchair'=>37,
			'price_per_uncoveredchair'=>25,
			'fac_id'=>2,
			'client_id'=>26
		],
		[
			'type'=>2,
			'minQty'=>400,
			'maxQty'=>600,
			'price_per_coveredchair'=>32,
			'price_per_uncoveredchair'=>20,
			'fac_id'=>2,
			'client_id'=>26
		],
		[
			'type'=>2,
			'minQty'=>600,
			'maxQty'=>800,
			'price_per_coveredchair'=>30,
			'price_per_uncoveredchair'=>18,
			'fac_id'=>2,
			'client_id'=>26
		],
		[
			'type'=>2,
			'minQty'=>800,
			'maxQty'=>1000,
			'price_per_coveredchair'=>55,
			'price_per_uncoveredchair'=>52,
			'fac_id'=>2,
			'client_id'=>26
		],
		[
			'type'=>2,
			'minQty'=>1000,
			'maxQty'=>10000,
			'price_per_coveredchair'=>52,
			'price_per_uncoveredchair'=>48,
			'fac_id'=>2,
			'client_id'=>26
		],
		[
			'type'=>3,
			'minQty'=>0,
			'maxQty'=>200,
			'price_per_coveredchair'=>48,
			'price_per_uncoveredchair'=>46,
			'fac_id'=>2,
			'client_id'=>26
		],
		[
			'type'=>3,
			'minQty'=>200,
			'maxQty'=>400,
			'price_per_coveredchair'=>46,
			'price_per_uncoveredchair'=>40,
			'fac_id'=>2,
			'client_id'=>26
		],
		[
			'type'=>3,
			'minQty'=>400,
			'maxQty'=>600,
			'price_per_coveredchair'=>38,
			'price_per_uncoveredchair'=>38,
			'fac_id'=>2,
			'client_id'=>26
		],
		[
			'type'=>3,
			'minQty'=>600,
			'maxQty'=>800,
			'price_per_coveredchair'=>30,
			'price_per_uncoveredchair'=>20,
			'fac_id'=>2,
			'client_id'=>26
		],
		[
			'type'=>3,
			'minQty'=>800,
			'maxQty'=>1000,
			'price_per_coveredchair'=>28,
			'price_per_uncoveredchair'=>18,
			'fac_id'=>2,
			'client_id'=>26
		],
		[
			'type'=>3,
			'minQty'=>1000,
			'maxQty'=>10000,
			'price_per_coveredchair'=>25,
			'price_per_uncoveredchair'=>15,
			'fac_id'=>2,
			'client_id'=>26
		]	
	];
		
		foreach($chairs as $chair)
            {
                App\Chair::create($chair);
            }
    }
}
